// Generated by CoffeeScript 1.4.0
(function() {

  describe("Ajax", function() {
    it("AjaxCore should exist in Greed", function() {
      expect("AjaxCore" in window.Greed).toBe(true);
    });
    return;
    it("ajax() should exist in Greed", function() {
      expect(("ajax" in window.Greed) && typeof window.Greed.ajax === "function").toBe(true);
    });
    return;
    it("ajaxJSON() should exist in Greed", function() {
      expect(("ajaxJSON" in window.Greed) && typeof window.Greed.ajaxJSON === "function").toBe(true);
    });
  });

}).call(this);
