// Generated by CoffeeScript 1.4.0
(function() {

  if (!('Greed' in window)) {
    window.Greed = {};
  }

  (function(Greed) {
    var AjaxCore, ajaxJSON, emptyFunc, _doc, _g;
    _g = Greed || {};
    _doc = window.document;
    _g.active = 0;
    emptyFunc = function() {};
    AjaxCore = function() {
      this.defaults = {
        url: '',
        type: 'POST',
        data: {},
        success: void 0,
        error: void 0
      };
      return this.xhr = new XMLHttpRequest();
    };
    AjaxCore.prototype.xhr = void 0;
    AjaxCore.prototype.onAjaxTimeout = function() {
      var that;
      that = this;
      return function() {
        console.log('ajax timeout');
        that.xhr.onreadystatechange = emptyFunc;
        that.xhr.abort();
      };
    };
    AjaxCore.prototype.onReadyStateChange = function() {
      var that;
      that = this;
      return function() {
        var result;
        if (that.xhr.readyState === 4) {
          console.log('xhr is ready');
          that.onReadyStateChange = emptyFunc;
          if (that.xhr.status === 200) {
            result = that.xhr.responseText;
          }
        }
      };
    };
    _g.AjaxCore = AjaxCore;
    _g.ajax = function(url, options) {
      return new _g.AjaxCore(url, options);
    };
    ajaxJSON = function(url, options) {
      return console.log('ajax json method');
    };
  })(Greed);

}).call(this);
