// Generated by CoffeeScript 1.4.0
(function() {
  var Greed, _g;

  Greed = function() {
    console.log('greed.js is my personal utility library');
    return console.log('core module ');
  };

  window.Greed = Greed;

  _g = window.Greed;

}).call(this);
