// Generated by CoffeeScript 1.4.0
(function() {
  var Greed;

  Greed = function() {
    console.log('greed.js is my personal utility library');
    console.log('core module ');
  };

  /*
  determne type of given object
  */


  Greed.is = function(type, obj) {
    var clas;
    clas = Object.prototype.toString.call(obj).slice(8, -1);
    return obj !== void 0 && obj !== null && clas === type;
  };

  Greed.is.prototype.TYPE_FUNCTION = "Function";

  Greed.is.prototype.TYPE_STRING = "String";

  Greed.is.prototype.TYPE_DATE = "Date";

  Greed.is.prototype.TYPE_ARRAY = "Array";

  Greed.is.prototype.TYPE_OBJECT = "Object";

  Greed.is.prototype.TYPE_NUMBER = "Number";

  /*
  class editing utilities
  */


  Greed.addClass = function(el, clas) {
    if (el != null) {
      el.classList.add(clas);
    }
  };

  Greed.removeClass = function(el, clas) {
    if (el != null) {
      el.classList.remove(clas);
    }
  };

  Greed.hasClass = function(el, clases) {
    var clas, _i, _len;
    if (!el) {
      return;
    }
    if (!Array.isArray(clases)) {
      clases = [clases];
    }
    for (_i = 0, _len = clases.length; _i < _len; _i++) {
      clas = clases[_i];
      if (el.classList.contains(clas)) {
        return true;
      }
    }
    return false;
  };

  window.Greed = Greed;

  window._g = window.Greed;

}).call(this);
